[build.environment]
NPM_FLAGS = "--force"

[build]
publish = "build"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[dev]
framework = "vite"
command = "npm start -- --no-open"
targetPort = 5173
